# Generated by Django 3.2.3 on 2021-09-30 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.timestampedmodel')),
                ('state_of_residence', models.CharField(default='location', max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('api.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.timestampedmodel')),
                ('name', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='image')),
                ('seller', models.ForeignKey(default='Location', on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
            bases=('api.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.timestampedmodel')),
                ('name', models.TextField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.TextField(max_length=120)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            bases=('api.timestampedmodel',),
        ),
    ]
