# Generated by Django 3.2.3 on 2021-09-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='location',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
